version: '3'
services:
  front:
    depends_on:
      - "back"
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=back
  back:
    image: todobackend
    restart: always
    ports:
      - 3001:3001
  todotests:
    depends_on:
      - "back"
      - "front"
    restart: always
    image: todotests
    environment: 
      - FRONT_HOST=front